version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload 