name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. リポジトリのコードを取得
      - name: Check out
        uses: actions/checkout@v3

      # 2. GCP 認証 (サービスアカウント JSON を使う例)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. gcloud CLI のセットアップ
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 4. Cloud Run にデプロイ
      - name: Deploy backend
        run: |
          gcloud run deploy backend \
            --source ./backend/src/chatbot \
            --region asia-northeast1 \
            # --service-account genai-backend-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --no-allow-unauthenticated
